version: '3.4'

services:
  mysite:
    image: mysite:dev
    container_name: MySite
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "MySite"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_mysite$
    volumes:
      - /System/Volumes/Data/Previous Content/Data/KhizoOo/Projects/Untitled/Portfolio/MySite:/app
      - /System/Volumes/Data/Previous Content/Data/KhizoOo/Projects/Untitled/Portfolio:/src
      - /Users/khizooo/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_mysite$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_mysite$ \"/app/bin/Debug/net7.0/MySite.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true